### PR TITLE
Resolve Wikidata URIs via LDF endpoint and LC URIs using HEAD requests

### LINKED ISSUE #912: Faster lookup of Wikidata URIs using LDF endpoint
## At which URL did you encounter the problem?
http://dev.finto.fi/yso-paikat/fi/page/p105181

## What steps will reproduce the problem?
1. Open a YSO Places page for a major place such as a country (e.g. Taiwan above)
2. Wait for the mappings to appear

## What is the expected output? What do you see instead?

This can take a long time, especially when the page is accessed the first time. In the case of Taiwan above, the Wikidata mapping takes a while to load and then fails entirely.

The problem is that URI lookups from Wikidata can be really slow, especially for entities with a lot of statements. Wikidata takes a long time to respond, then returns a large RDF blob, which takes a long time to parse etc. It's very inefficient since we essentially need only two things: the label and the Wikipedia sitelinks.

A potential solution would be using the [Wikidata LDF endpoint](https://query.wikidata.org/bigdata/ldf), which allows querying by simple query patterns and is really fast. We would probably have to perform two queries though:

1. labels i.e. subject=itemURI, property=rdfs:label, object=unbound
2. sitelinks i.e. subject=unbound, property=schema:about, object=itemURI

The result of each query would be a graph. These could be merged to a single graph and then used the same way that the response graph is currently used.

To implement this, we would need to implement a special case handler for Wikidata URIs that replaces the normal URI lookup mechanism.

### LINKED ISSUE #915: Faster lookup of LCSH labels using HEAD requests
## At which URL did you encounter the problem?
http://finto.fi/yso/fi/page/p1191

## What steps will reproduce the problem?
1. Go to a YSO concept page with a LCSH link

## What is the expected output? What do you see instead?

Loading LCSH labels is sometimes very slow. Skosmos is resolving the URI and requesting all the RDF triples in follow-your-nose Linked Data style. The LCSH server (id.loc.gov) can be slow to respond and responses can be large in some cases.

But we actually need only the LCSH label. LCSH URIs can be looked up using lightweight HEAD requests and the response includes a `X-PrefLabel` HTTP header with the label:

```
$ curl -I http://id.loc.gov/authorities/subjects/sh85145789
HTTP/1.1 303 SEE OTHER
Date: Wed, 29 Jan 2020 15:37:30 GMT
Content-Length: 0
Connection: keep-alive
Set-Cookie: __cfduid=d0aab41e7be00e8bddcc646f2047eaed31580312249; expires=Fri, 28-Feb-20 15:37:29 GMT; path=/; domain=.loc.gov; HttpOnly; SameSite=Lax
Location: http://id.loc.gov/authorities/subjects/sh85145789.html
Vary: Accept
X-URI: http://id.loc.gov/authorities/subjects/sh85145789
X-PrefLabel: Waves
cache-control: public, max-age=2419200
X-Varnish: 33593423
Age: 0
Via: 1.1 varnish-v4
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD, POST, GET, OPTIONS
Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
CF-Cache-Status: DYNAMIC
Server: cloudflare
CF-RAY: 55cc49aa5884fe50-HEL
```

Similar to #912, we could have a special case for LCSH URIs (or in general, all URIs beginning with id.loc.gov) that performs only a HEAD request instead of the normal lookup mechanism.

### PR DESCRIPTION
**Pull request by osma**
This PR refactors and modularizes the lookup/resolution mechanism for remote URIs, that is, URIs that Skosmos knows nothing about. 

There is a new Resolver class which knows which resolution mechanism to use for a particular URI. Wikidata URIs are looked up via the LDF endpoint (fixes #912); HEAD requests are used for LCSH and other LC vocabularies (fixes #915); and for everything else, a generic Linked Data mechanism (just retrieve the URI and ask for RDF) is used, as before.

Unfortunately, it turns out that the Wikidata LDF endpoint cannot currently handle language tags. I've reported this to the Wikidata list. If the issue isn't fixed soon, then that mechanism has to be disabled for now - perhaps the Wikidata SPARQL endpoint could be used instead, although it may be less reliable than the LDF endpoint.

I'm keeping this just as a draft PR for now, until there is more clarity on the LDF endpoint issue. I just want to see the automated QA reports.

### CODE REVIEW

File: model/resolver/Resolver.php [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+     * result as an ExternalResource.
+     * @param string $uri URI to resolve
+     * @return EasyRdf\Resource
+     */
+    public function resolve(string $uri, int $timeout): ?EasyRdf\Resource {
+        if (preg_match('|http://id.loc.gov/[^/]+/[^/]+/.+|', $uri)) {
+            $res = new LOCResource($uri);
+        } elseif ($this->startsWith('http://www.wikidata.org/entity/', $uri)) {
+            $res = new LDFResource($uri, 'https://query.wikidata.org/bigdata/ldf');
+        } else {
```
Comment (osma) [inline model/resolver/Resolver.php]: Codacy Issue found: [The method resolve uses an else expression. Else is never necessary and you can simplify the code to work without else.](https://app.codacy.com/manual/NatLibFi/Skosmos/pullRequest?prid=4951447)

**Comment by osma** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 10
           

Complexity increasing per file
==============================
- model/ConceptPropertyValue.php  1
- model/resolver/Resolver.php  3
- model/resolver/LDFResource.php  2
- model/resolver/LOCResource.php  4
- model/resolver/LinkedDataResource.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/NatLibFi/Skosmos/pullRequest?prid=4951447&bid=16365795)

File: model/resolver/LDFResource.php [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+        $this->uri = $uri;
+        $this->ldfEndpoint = $ldfEndpoint;
+    }
+    
+    public function resolve(int $timeout) : ?EasyRdf\Resource {
+        try {
+            // change the timeout setting for external requests
+            $httpclient = EasyRdf\Http::getDefaultHttpClient();
+            $httpclient->setConfig(array('timeout' => $timeout));
+            EasyRdf\Http::setDefaultHttpClient($httpclient);
```
Comment (osma) [inline model/resolver/LDFResource.php]: Codacy Issue found: [Avoid using static access to class 'EasyRdf\Http' in method 'resolve'.](https://app.codacy.com/manual/NatLibFi/Skosmos/pullRequest?prid=4951447)

File: model/resolver/LinkedDataResource.php [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+    public function __construct(string $uri) {
+        $this->uri = $uri;
+    }
+    
+    public function resolve(int $timeout) : ?EasyRdf\Resource {
+        // prevent parsing errors for sources which return invalid JSON (see #447)
+        // 1. Unregister the legacy RDF/JSON parser, we don't want to use it
+        EasyRdf\Format::unregister('json');
+        // 2. Add "application/json" as a possible MIME type for the JSON-LD format
+        $jsonld = EasyRdf\Format::getFormat('jsonld');
```
Comment (osma) [inline model/resolver/LinkedDataResource.php]: Codacy Issue found: [Avoid using static access to class 'EasyRdf\Format' in method 'resolve'.](https://app.codacy.com/manual/NatLibFi/Skosmos/pullRequest?prid=4951447)

File: model/resolver/LinkedDataResource.php [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+        $mimetypes = $jsonld->getMimeTypes();
+        $mimetypes['application/json'] = 0.5;
+        $jsonld->setMimeTypes($mimetypes);
+
+        try {
+            // change the timeout setting for external requests
+            $httpclient = EasyRdf\Http::getDefaultHttpClient();
+            $httpclient->setConfig(array('timeout' => $timeout));
+            EasyRdf\Http::setDefaultHttpClient($httpclient);
```
Comment (osma) [inline model/resolver/LinkedDataResource.php]: Codacy Issue found: [Avoid using static access to class 'EasyRdf\Http' in method 'resolve'.](https://app.codacy.com/manual/NatLibFi/Skosmos/pullRequest?prid=4951447)

File: model/resolver/LinkedDataResource.php [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+        EasyRdf\Format::unregister('json');
+        // 2. Add "application/json" as a possible MIME type for the JSON-LD format
+        $jsonld = EasyRdf\Format::getFormat('jsonld');
+        $mimetypes = $jsonld->getMimeTypes();
+        $mimetypes['application/json'] = 0.5;
+        $jsonld->setMimeTypes($mimetypes);
+
+        try {
+            // change the timeout setting for external requests
+            $httpclient = EasyRdf\Http::getDefaultHttpClient();
```
Comment (osma) [inline model/resolver/LinkedDataResource.php]: Codacy Issue found: [Avoid using static access to class 'EasyRdf\Http' in method 'resolve'.](https://app.codacy.com/manual/NatLibFi/Skosmos/pullRequest?prid=4951447)

File: model/resolver/LDFResource.php [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+
+    public function __construct(string $uri, string $ldfEndpoint) {
+        $this->uri = $uri;
+        $this->ldfEndpoint = $ldfEndpoint;
+    }
+    
+    public function resolve(int $timeout) : ?EasyRdf\Resource {
+        try {
+            // change the timeout setting for external requests
+            $httpclient = EasyRdf\Http::getDefaultHttpClient();
```
Comment (osma) [inline model/resolver/LDFResource.php]: Codacy Issue found: [Avoid using static access to class 'EasyRdf\Http' in method 'resolve'.](https://app.codacy.com/manual/NatLibFi/Skosmos/pullRequest?prid=4951447)

File: model/resolver/LinkedDataResource.php [hunk 7]
```diff
@@ -0,0 +1,36 @@
...
+            $httpclient->setConfig(array('timeout' => $timeout));
+            EasyRdf\Http::setDefaultHttpClient($httpclient);
+
+            $graph = EasyRdf\Graph::newAndLoad(EasyRdf\Utils::removeFragmentFromUri($this->uri));
```
Comment (osma) [inline model/resolver/LinkedDataResource.php]: Codacy Issue found: [Avoid using static access to class 'EasyRdf\Utils' in method 'resolve'.](https://app.codacy.com/manual/NatLibFi/Skosmos/pullRequest?prid=4951447)

File: model/ConceptPropertyValue.php [hunk 8]
```diff
@@ -87,6 +96,15 @@ public function getUri()
         return $this->resource->getUri();
     }
 
+    public function getExVocab()
+    {
+        if ($this->isExternal()) {
+            return $this->vocab;
+        } else {
```
Comment (osma) [inline model/ConceptPropertyValue.php]: Codacy Issue found: [The method getExVocab uses an else expression. Else is never necessary and you can simplify the code to work without else.](https://app.codacy.com/manual/NatLibFi/Skosmos/pullRequest?prid=4951447)

File: model/resolver/LinkedDataResource.php [hunk 9]
```diff
@@ -0,0 +1,36 @@
...
+    private $uri;
+
+    public function __construct(string $uri) {
+        $this->uri = $uri;
+    }
+    
+    public function resolve(int $timeout) : ?EasyRdf\Resource {
+        // prevent parsing errors for sources which return invalid JSON (see #447)
+        // 1. Unregister the legacy RDF/JSON parser, we don't want to use it
+        EasyRdf\Format::unregister('json');
```
Comment (osma) [inline model/resolver/LinkedDataResource.php]: Codacy Issue found: [Avoid using static access to class 'EasyRdf\Format' in method 'resolve'.](https://app.codacy.com/manual/NatLibFi/Skosmos/pullRequest?prid=4951447)

File: model/resolver/LOCResource.php [hunk 10]
```diff
@@ -0,0 +1,34 @@
...
+        // guess the concept scheme based on the URI
+        if (preg_match('|(http://id.loc.gov/[^/]+/[^/]+)/.*|', $this->uri, $matches)) {
+            $graph->addResource($this->uri, 'skos:inScheme', $matches[1]);
+        }
+
+        $opts = array('http' => array('method'=>'HEAD',
+                                      'user_agent' => 'Skosmos',
+                                      'timeout' => $timeout));
+        $context  = stream_context_create($opts);
+        $fd = fopen($this->uri, 'rb', false, $context);
```
Comment (osma) [inline model/resolver/LOCResource.php]: Codacy Issue found: [Avoid variables with short names like $fd. Configured minimum length is 3.](https://app.codacy.com/manual/NatLibFi/Skosmos/pullRequest?prid=4951447)
