### PR TITLE
Do not treat 0 as boolean value in the REST controller

### LINKED ISSUE #1275: Searching via API using the search term '0' without asterisk (0*) fails
## At which URL did you encounter the problem?
https://api.dev.finto.fi/rest/v1/ykl/search?query=0

## What steps will reproduce the problem?
1. Go https://api.finto.fi/rest/v1/ykl/search?query=0 

## What is the expected output? What do you see instead?
It turned out that the fixes in the PR #1261 do not work completely (mostly it works :+1: ). There is still a problem with the searches with zeros ('0') if you do not use a trailing asterisk with the number zero. 

[https://api.finto.fi/rest/v1/ykl/search?query=0](https://api.finto.fi/rest/v1/ykl/search?query=0) should return a result containing the concept [https://dev.finto.fi/ykl/en/page/0](https://dev.finto.fi/ykl/en/page/0) (http://urn.fi/URN:NBN:fi:au:ykl:0) but it returns an empty result. 

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
FF

### PR DESCRIPTION
**Pull request by kinow**
## Reasons for creating this PR

Prevent `0` being treated as a truthy value in the REST controller. Complements #1261 

## Link to relevant issue(s), if any

- Closes #1275

## Description of the changes in this PR

Same fix as #1261 

## Known problems or uncertainties in this PR

None.

## Checklist

- [x] phpUnit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if not, explain why below)
- [x] The PR doesn't introduce unintended code changes (e.g. empty lines or useless reindentation)

### CODE REVIEW

**Comment by osma** [comment]
Can you please rebase @kinow, so we can see if #1277 worked?

**Comment by osma** [comment]
This is now overlapping with #1267 by @miguelvaara  - there are changes to the same lines in ConceptSearchParameters.getSearchTerm. These need to be consolidated somehow. Maybe simply by merging one first, then fixing the conflicts in the other.

**Comment by kinow** [comment]
Rebased, GH Actions working :toolbox: thanks @osma !

**Comment by osma** [comment]
The code looks good - I think the easiest way forward is to merge this first and then sort out the conflicts in PR #1267, as that one is still a bit WIP (at least the PR description is outdated).

The only thing I wonder about is the title of this PR (and the commit message) which says "Do not treat 0 as truthy value". Isn't the point actually the opposite - "Do not treat 0 as a **non-truthy** (i.e. false) value"?

**Comment by kinow** [comment]
You're right! s/truthy/boolean , WDYT?

**Comment by osma** [comment]
Sounds good!

File: tests/ConceptSearchParametersTest.php [hunk 1]
```diff
@@ -86,6 +86,26 @@ public function testGetSearchTerm() {
         $this->assertEquals('test', $params->getSearchTerm());
     }
 
+    /**
+     * For https://github.com/NatLibFi/Skosmos/issues/1275, to verify
+     * that querying for `0` (zero) does not evaluate it as a truthy
```
Comment (osma) [inline tests/ConceptSearchParametersTest.php:91]: s/truthy/boolean/ here as well?

Comment (kinow) [reply tests/ConceptSearchParametersTest.php:91]: Oh, missed that one. Just a sec.

Comment (kinow) [reply tests/ConceptSearchParametersTest.php]: Done. That should be the last one ™

Comment (osma) [reply tests/ConceptSearchParametersTest.php]: Famous last words!

**Comment by osma** [comment]
Will do one final test round and then merge!

**Comment by osma** [comment]
Works like a charm! Thanks a lot @kinow !
